### ISSUE TITLE
ModuleNotFoundError despite install going smoothly

### ISSUE THREAD

**Issue by mrtolkien** [Canisback/roleML#1]
Install output:

`install roleml
Collecting roleml
  Downloading https://files.pythonhosted.org/packages/94/6f/d7a5a10b97dac159270c3eac51c7a1aea4b89bb037b348d8d3a846eaa014/roleml-0.1.4-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 5.0MB/s 
Requirement already satisfied: numpy in /usr/local/anaconda3/lib/python3.7/site-packages (from roleml) (1.15.4)
Requirement already satisfied: pandas in /usr/local/anaconda3/lib/python3.7/site-packages (from roleml) (0.23.4)
Requirement already satisfied: scikit-learn in /usr/local/anaconda3/lib/python3.7/site-packages (from roleml) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/anaconda3/lib/python3.7/site-packages (from roleml) (3.0.2)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/anaconda3/lib/python3.7/site-packages (from pandas->roleml) (2.7.5)
Requirement already satisfied: pytz>=2011k in /usr/local/anaconda3/lib/python3.7/site-packages (from pandas->roleml) (2018.7)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/anaconda3/lib/python3.7/site-packages (from scikit-learn->roleml) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/anaconda3/lib/python3.7/site-packages (from matplotlib->roleml) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/anaconda3/lib/python3.7/site-packages (from matplotlib->roleml) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/anaconda3/lib/python3.7/site-packages (from matplotlib->roleml) (2.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas->roleml) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->roleml) (40.6.3)
Installing collected packages: roleml
Successfully installed roleml-0.1.4
`

Console output:
`from roleml import roleml
/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.20.2 when using version 0.20.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b31d322cfce4>", line 1, in <module>
    from roleml import roleml
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/roleml/roleml.py", line 31, in <module>
    roleml_model = joblib.load(os.path.join(os.path.dirname(__file__), "role_identification_model.sav"))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/local/anaconda3/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 352, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 195, in read
    array = self.read_array(unpickler)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 119, in read_array
    array = pickle.load(unpickler.file_handle)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'`

**Comment by mrtolkien** [comment]
Fixed by updating numpy from 1.15.4 to 1.16.2
