### ISSUE TITLE
Error when running against some games

### ISSUE THREAD

**Issue by paz** [Canisback/roleML#11]
Error is
```
Traceback (most recent call last):
  File "role.py", line 12, in <module>
    print(roleml.predict(match, timeline))
  File "/usr/local/lib/python3.6/dist-packages/roleml/roleml.py", line 215, in predict
    df["role"] = roleml_model.predict(df.drop(["participantId"], axis=1))
  File "/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py", line 612, in predict
    proba = self.predict_proba(X)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py", line 656, in predict_proba
    X = self._validate_X_predict(X)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py", line 412, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/tree/_classes.py", line 380, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

I see it on stackoverflow here: https://datascience.stackexchange.com/questions/11928/valueerror-input-contains-nan-infinity-or-a-value-too-large-for-dtypefloat32

The game IDs I found with it are 283231298 and 283214895

I am using 64-bit ubuntu with python 3.6
[https://paz.pw/75213f5612aebfc7fa0e332eb467d1d5.png](https://paz.pw/75213f5612aebfc7fa0e332eb467d1d5.png)
```
root@peachy:~# file /usr/bin/python3.6
/usr/bin/python3.6: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=287763e881de67a59b31b452dd0161047f7c0135, stripped
root@peachy:~# uname -m
x86_64
```

**Comment by Canisback** [comment]
The first one is an ARAM, there is no role to check and summoner spells that make that error. The second game is too short.

**Comment by paz** [comment]
Oh , it must have been remake? My bad, sorry
